// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd9PcnTRRlilMBPRI8Ox84wG6IeN8hYwQ',
    appId: '1:926138501493:web:c7e2bbadc4007f6a13ab3c',
    messagingSenderId: '926138501493',
    projectId: 'bizfuel-958e9',
    authDomain: 'bizfuel-958e9.firebaseapp.com',
    storageBucket: 'bizfuel-958e9.appspot.com',
    measurementId: 'G-8LSB4SBW0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV1zTuoyxUF1yiRVExEk2ePpDXEKnyoY8',
    appId: '1:926138501493:android:edcbaf037582accd13ab3c',
    messagingSenderId: '926138501493',
    projectId: 'bizfuel-958e9',
    storageBucket: 'bizfuel-958e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgLKPR-W6mP46sGjbqlm7VzOVgK2mmpk0',
    appId: '1:926138501493:ios:f2f409dff9901dba13ab3c',
    messagingSenderId: '926138501493',
    projectId: 'bizfuel-958e9',
    storageBucket: 'bizfuel-958e9.appspot.com',
    iosBundleId: 'com.example.bizfuel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgLKPR-W6mP46sGjbqlm7VzOVgK2mmpk0',
    appId: '1:926138501493:ios:f2f409dff9901dba13ab3c',
    messagingSenderId: '926138501493',
    projectId: 'bizfuel-958e9',
    storageBucket: 'bizfuel-958e9.appspot.com',
    iosBundleId: 'com.example.bizfuel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd9PcnTRRlilMBPRI8Ox84wG6IeN8hYwQ',
    appId: '1:926138501493:web:4cb6d47d8f91a68013ab3c',
    messagingSenderId: '926138501493',
    projectId: 'bizfuel-958e9',
    authDomain: 'bizfuel-958e9.firebaseapp.com',
    storageBucket: 'bizfuel-958e9.appspot.com',
    measurementId: 'G-K9S77YR5YL',
  );
}
